language: en

pipeline:
- name: ResponseSelector
  retrieval_intent: chitchat
  epochs: 25
# will be selected by the Suggested Config feature

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 10
- name: RulePolicy
